import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "About App",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
  return (
    <>
      <nav>About Nav</nav>
      <main>{children}</main>
    </>
  );
}
